questions:
  - type: text
    name: Nennspannung
    message: "Nennspannung? (Format: 96kV bis 123kV)"
    validate: '^(9[6-9]|10[0-9]|11[0-9]|12[0-3])kV$'
  - type: select
    name: Einspeisungsart
    message: "Einspeisungsart?"
    choices:
      - einseitig
      - beidseitig
  - type: text
    name: UWLastPaare
    message: "Versorgte UWs mit Last? (Format: SE=15MW,N=20MW,...)"
    validate: '^(SE|EE|N)=\d+(\.\d+)?MW(,(SE|EE|N)=\d+(\.\d+)?MW)*$'
